project:
  type: website
  output-dir: docs
  
website:
  title: "Research in R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/miukeurhub/gmp-wasting-nepal
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Mugi Silih Mulyadi"

format:
  html:
    theme: cerulean
    toc: true

editor: source

